### ISSUE TITLE
Canonical macOS root paths break linting with TypeScript parser

### ISSUE THREAD

**Issue by kopischke** [kopischke/microESLint.nova#3]
On Mac systems, `/Volumes/<Drive name (defaults to “Macintosh HD”)>` is the canonical root path returned by all file management Cocoa APIs, and hence by Nova’s APIs. That `<Drive name>` path is actually a symbolic link to the UNIX root path `/`, a situation which the TypeScript ESLint parser apparently is unable to handle (see #2 _passim_ for notes on this). 

Tentatively, there seem to be two solutions to this, both of which have stood up to (cursory) testing:

- “UNIXalise” all paths, i.e. remove `/Volumes/<Drive name>` from all qualified paths.
- Relativise all paths, i.e. make them relative to the config file directory.

**Comment by natesilva** [comment]
For the first solution, it will need special handling for external drives as they require the `/Volumes/<Drive name>` format. The correct path will be whatever is returned by the Node function `path.resolve('.')` when run from that directory.

I don’t see a way to detect whether a drive is external from the Nova Extensions API.

**Comment by kopischke** [comment]
Actually, I think I got that one solved:

![Linting with typeScript](https://p103.p0.n0.cdn.getcloudapp.com/items/9Zu0rjNZ/Linting%20with%20TypeScript.png?v=856aef1ca070c12efb8915e61dcbc889)

As it turns out, you don’t need to know if a drive is external because the quirk of the Nova path resolving function that got us into this mess can also be leveraged to get us out of it again. Specifically `nova.path.normalize()`will expand `/` to `/Volumes/<Drive name>`. This works for me:

```js
function nixalize (path) {
  const normalised = nova.path.normalize(path)
  if (!nova.path.isAbsolute(normalised)) return normalised

  const parts = nova.path.split(normalised)
  if (parts.length <= 2) return normalised

  const root = nova.path.normalize('/')
  const same = nova.path.split(root).every((el, idx) => parts[idx] === el)
  return same
    ? nova.path.join(...['/'].concat(parts.slice(3)))
    : normalised
}
```

As a German, I find this quintessentially [Münchhausenesque](https://en.wikipedia.org/wiki/Baron_Munchausen) solution deeply satisfying.

Anyway, release coming up ASAP.

**Comment by kopischke** [comment]
I’ve pushed all the fixes to the [dev branch](https://github.com/kopischke/microESLint.nova/tree/dev). @natesilva would you like (and do you have the opportunity) to test it before I pull the trigger on the release?

**Comment by natesilva** [comment]
Testing now.

**Comment by natesilva** [comment]
It works!
